name: leon
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.12=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backcall==0.2.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - executing==2.0.1
      - filelock==3.13.1
      - frozenlist==1.4.0
      - fsspec==2023.12.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - idna==3.6
      - importlib-resources==6.1.1
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - pandas==2.0.3
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.1.0
      - pkgutil-resolve-name==1.3.10
      - prompt-toolkit==3.0.41
      - protobuf==4.25.1
      - psutil==5.9.7
      - psycopg2-binary==2.9.9
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - ray==2.8.1
      - referencing==0.31.1
      - requests==2.31.0
      - rpds-py==0.13.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - sympy==1.12
      - threadpoolctl==3.2.0
      - tomli==2.0.1
      - torch==2.1.1
      - torchmetrics==1.2.1
      - tqdm==4.66.1
      - traitlets==5.14.0
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.1.0
      - wandb==0.16.1
      - wcwidth==0.2.12
      - yarl==1.9.3
      - zipp==3.17.0
prefix: /data1/chenx/softwares/miniconda3/envs/leon
